// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wexqqubmlqsktcfiznpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleHFxdWJtbHFza3RjZml6bnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzgyNTQsImV4cCI6MjA2ODQxNDI1NH0.p9yfoHR8B6i2Jfd_PK_NJbaArfrZmEuocwLpEM2uR-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});