// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whtgdouslmogsrrevxkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodGdkb3VzbG1vZ3NycmV2eGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzE0MTIsImV4cCI6MjA2MzgwNzQxMn0.XxH3KvhaSY7P330maMVB30RhBY8M8bl3ec52O5O5w4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});